import type { Metadata } from "next";
import "./styles/globals.scss";
import Header from "./components/base/Header/Header";
import Footer from "./components/base/Footer/Footer";
import Container from "./components/common/Container/Container";
import StoreProvider from "@/redux/storeProvider";
import Loader from "./components/base/Loader/Loader";
import { nunito } from "./fonts/fonts";
import Navbar from "./components/base/Navbar/NavBar";
import "react-circular-progressbar/dist/styles.css";
import HomePage from "./components/pages/HomePage/HomePage";

//import { preloadFlags } from "../../utils/preloadFlags";

export const metadata: Metadata = {
    title: "☆ PerformStars ☆",
    description: "Generated by create next app",
    icons: {
        icon: "/img/icon.png",
    },
};

export default async function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    // preloadFlags();

    return (
        <StoreProvider>
            <html lang="en" className={nunito.className}>
                <body>
                    <Loader />
                    <HomePage>{children}</HomePage>
                </body>
            </html>
        </StoreProvider>
    );
}
